faka/app/faka/__init__.py
# -*- coding=utf-8 -*-
from flask import Blueprint

faka = Blueprint('faka', __name__)

from . import views

faka/app/faka/views.py
#-*- coding=utf-8 -*-
import datetime
from flask import jsonify, redirect, render_template, request, session, flash, url_for
from flask_login import login_user, logout_user, login_required, current_user
from . import faka
from .. import db
from ..models import *
import requests
from ..payjs import getqr


@faka.route('/')
def index():
    return render_template('faka/index.html')


@faka.route('/getkm', methods=["POST", "GET"])
def getkm():
    if request.method == 'POST':
        lx = request.form.get('tqm', type=int)
        orders = Order.query.filter_by(lx=lx).all()
        if len(orders) == 0:
            return render_template('faka/getkm.html', orders=None)
        else:
            return render_template('faka/getkm.html', orders=orders)
    return render_template('faka/getkm.html')


@faka.route('/Selgo', methods=["POST"])
def Selgo():
    cateid = request.form.get('cateid')
    goods = db.session.query(Good).join(
        Category, Good.cate_id == Category.cateid).filter(Category.cateid == cateid,Good.good_status==True).all()
    base = u"<option id='{goodid}' imgs='assets/goodsimg/df.jpg' value='{goodid}' kc='{kc}' title='{price}' alt = '{info}'>{goodname}</option>"
    s = u'<option>请选择商品</option>'
    for good in goods:
        kc = db.session.query(KM).join(Good, KM.good_id == Good.good_id).filter(
            KM.km_status == True, Good.good_id == good.good_id).count()
        s += base.format(goodid=good.good_id,
                         goodname=good.good_name, price=good.good_price, kc=kc, info=good.good_info)
    return jsonify({'msg': s})


@faka.route('/Checkgo', methods=["POST"])
def Checkgo():
    goodid = request.form.get('goodid')
    kc = db.session.query(KM).join(Good, KM.good_id == Good.good_id).filter(
        KM.km_status == True, Good.good_id == goodid).count()
    if kc < 0:
        retdata = {'code': -1}
    else:
        retdata = {'code': 1}
    return jsonify(retdata)


@faka.route('/CreateOrder', methods=["POST"])
def CreateOrder():
    trade_id = request.form.get('out_trade_no')
    good_id = request.form.get('gid')
    lx = request.form.get('rel')
    feedback = request.scheme + '://' + request.host + '/check_order'
    try:
        order = Order(trade_id=trade_id, lx=lx, good_id=good_id)
        db.session.add(order)
        db.session.commit()
        good = Good.query.filter_by(good_id=good_id).first()
        qr = getqr(money=good.good_price, tradeid=trade_id, feedback=feedback)
        #qr="weixin://wxpay/"
        if qr == False:
            retdata = {'code': -1}
        else:
            retdata = {'code': 0, 'qr': qr}
    except Exception as e:
        print(e)
        retdata = {'code': -1}
    return jsonify(retdata)


@faka.route('/check_order', methods=["POST"])
def check_order():
    tradeid = request.form.get('out_trade_no')
    return_code = request.form.get('return_code', type=int)
    if return_code == 1:
        order = Order.query.filter_by(trade_id=tradeid).first()
        if order.trade_status == False:
            # 订单信息更新
            order.endtime = datetime.datetime.now()
            order.trade_status = True
            # 商品信息更新
            good = Good.query.filter_by(good_id=order.good_id).first()
            good.good_sales += 1  # 销量加1
            km = KM.query.filter_by(
                good_id=good.good_id, km_status=True).first()
            km.km_status = False  # 已售出
            # 订单绑定卡密
            order.km_id = km.km_id
            db.session.add(order)
            db.session.add(good)
            db.session.add(km)
            db.session.commit()
    return 'callback success'


# 添加卡密
@faka.route('/admin/add_code/', methods=['POST', 'GET'])
@login_required
def add_code():
    if request.method == 'POST':
        good_id = request.form.get('goodid')
        kms = eval(request.form.get('km'))
        success, fail = 0, 0
        for km in kms:
            km = km.replace(' ', '')
            try:
                if KM.query.filter_by(km_value=km,good_id=good_id).count() == 0:
                    newkm = KM(km_value=km, good_id=good_id)
                    db.session.add(newkm)
                    db.session.commit()
                    success += 1
            except Exception as e:
                print(e)
                fail += 1
        msg = '成功{}个，失败{}个'.format(success, fail)
        return jsonify({'msg': msg})
    return render_template('admin/add_code.html')

faka/app/templates/faka/getkm.html
{%extends 'base.html'%} {%block title%} - 出售各类爬虫，接爬虫单子 {%endblock title%}
{%block content%}
<div class="list-group-item list-group-item-warning">
    注意事项：
    <br>
    <br> 1.联系方式也可以作为你的提卡凭证
    <br>2.必须等待付款完成自动跳转，不可提前关闭页面，否则会导致订单失效，后果自负
    <br>
</div>
<ul class="nav nav-tabs">
    <li class="active"><a href="{{url_for('faka.getkm')}}" data-toggle="tab">订单查询提卡</a></li>
    <li><a href="{{url_for('faka.index')}}">在线购买下单</a></li>
</ul>
<div class="list-group-item">
    <div id="myTabContent" class="tab-content">
        <form action="{{url_for('faka.getkm')}}" method="POST">
            <div class="form-group">
                <input type="text" name="tqm" id="tqm" value="" class="form-control text-center" placeholder="输入联系方式提取到您的卡密" required/>
            </div>
            <input type="submit" id="sub_query" class="btn btn-primary btn-block" value="提取卡密">
        </form>
    </div>
    <div class="form-group">
      <div class="panel panel-default">
            <div class="panel-body" id="ginfo">
                {%if orders%}
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>商品名</th>
                      <th>价格</th>
                      <th>购买时间</th>
                      <th>卡密</th>
                    </tr>
                  </thead>
                  <tbody>
                    {%for order in orders%}
                    <tr>
                      <td>{{db.session.execute('select a.good_name from goods a,orders b where a.good_id=b.good_id and b.trade_id={}'.format(order.trade_id)).fetchone()[0]}} </td>
                      <td>{{db.session.execute('select a.good_price from goods a,orders b where a.good_id=b.good_id and b.trade_id={}'.format(order.trade_id)).fetchone()[0]}}</td>
                      <td>{{order.starttime}}</td>
                      <td>{{order.km.km_value}}</td>
                    </tr>
                    {%endfor%}
                  </tbody>
                </table>
                {%endif%}
            </div>
        </div>
    </div>
{%endblock content%}

faka/app/templates/faka/index.html
{%extends 'base.html'%}

{%block title%}
 - 出售各类爬虫，接爬虫单子
{%endblock title%}


{%block content%}
  <div class="panel panel-info">
        <div class="list-group-item reed" style="background: #66bdff;">
          <h3 class="panel-title">
            <font color="#fff"><i class="fa fa-volume-up"></i>&nbsp;&nbsp;<b>购买须知<用户必看></b></font>
          </h3>
        </div>
        <table class="table table-bordered">
          <tbody>
            <tr>
              <td align="center"><font color="#808080">本站域名：{{domain}}</font></td>
              <td align="center"><font color="#808080">客服QQ:{{qq}}</font></td>
            </tr>

          </tbody>
        </table>
        <div class="list-group-item reed">

          <font style="color:#009ACD;font-weight: bold;">提取卡密后请尽快激活使用或保存好，系统定期清除被提取的卡密</font>
        </div>
        <div class="list-group-item reed">
          <font style="color:#556B2F;font-weight: bold;">付款后按提示点击确定跳转到提取页面，不可提前关闭窗口！否则无法提取到卡密！</font>
        </div>
        <div class="list-group-item reed">
          <font style="color:#008B00;font-weight: bold;">提取码是订单编号 或者 您的联系方式！</font>
        </div>





</div>
<ul class="nav nav-tabs">
  <li class="active"><a href="{{url_for('faka.index')}}" data-toggle="tab">在线购买下单</a></li>
  <li><a href="{{url_for('faka.getkm')}}" >订单查询提卡</a></li>
</ul>
<div class="list-group-item">
  <div id="myTabContent" class="tab-content">
  <div class="tab-pane fade in active" id="onlinebuy">
    <div class="form-group">
      <div class="input-group"><div class="input-group-addon">商品分类</div>
      <select name="tp_id" id="tp_tid" class="form-control" onchange="getPoint(this);">
          {%for cate in Category.query.order_by(Category.cateid.asc()).all()%}
          <option value="{{cate.cateid}}">{{cate.cate_name}}</option>
          {%endfor%}
      </select>
    </div></div>
    <div class="form-group">
      <div class="input-group"><div class="input-group-addon">选择商品</div>
      <select name="gid" id="gid" class="form-control" onchange="getPrice(this)">
      </select>
    </div></div>
    <div class="form-group">
      <div class="panel panel-default">
            <div class="panel-body" id="ginfo">
            </div>
        </div>
    </div>
  </div>
    <div class="form-group">
      <div class="input-group"><div class="input-group-addon">商品价格</div>
      <input type="text" name="need" id="need" class="form-control" disabled/>
    </div></div>

    <div class="form-group" style=" ">
      <div class="input-group"><div class="input-group-addon">商品库存</div>
      <input type="text" name="kc" id="kc" class="form-control" disabled/>
    </div></div>

    <div class="form-group">
      <div class="input-group"><div class="input-group-addon">联系方式</div>
      <input type="text" name="lx" id="lx" value="" class="form-control" placeholder="输入您的QQ,您的QQ号码也可以作为您的提取密码" required/>
    </div></div>

    <div class="form-group">
     <span class="btn btn-default btnSpan"  title="wxpay"><input type="radio" name="type" value="wxpay" class="pay" id="wxpay" value="wxpay" title="微信支付" checked><img alt="" src="http://11.qiao0.com/assets/wechat.ico" class="logo">微信支付</span>
      </div>
    </div>
    <input type="submit" id="submit_buy" class="btn btn-primary btn-block" value="立即购买">
  </div>

<script type="text/javascript">
  function IsPC() {
    var userAgentInfo = navigator.userAgent;
    var Agents = ["Android", "iPhone",
                "SymbianOS", "Windows Phone",
                "iPad", "iPod"];
    var flag = true;
    for (var v = 0; v < Agents.length; v++) {
        if (userAgentInfo.indexOf(Agents[v]) > 0) {
            flag = false;
            break;
        }
    }
    return flag;
  }

  var ispc=IsPC();
  function getPoint(e){
        var d = $(e).val();//获取该分类的ID
        var ii = layer.load(2, {shade:[0.1,'#fff']});
        $.ajax({
        type : "POST",
        url : "{{url_for('faka.Selgo')}}",
        data : {"cateid":d},
        dataType : 'json',
        success : function(data) {
            layer.close(ii);

          //$("#gid").empty();
          //$("#gid").append(data.msg);
          $("#gid").html(data.msg);
          $('#ginfo').html("");
          $('#ginfo').hide();
        },
        error:function(data){
          layer.close(ii);
          layer.msg('服务器错误');
          }
      });
}
//获取库存
function getKc(){
  var kc  = $("#gid option:selected").attr("kc");
  $('#kc').val(kc);
  $('#kc').attr("alt",kc);

}
//获取商品介绍
function getInfo(){
  $('#ginfo').show();
  var alt  = $("#gid option:selected").attr("alt");
  if(alt == "" || alt == null){
    $('#ginfo').html("该商品无介绍");
  }else{
    $('#ginfo').html(alt);
  }

}
//获取价格
function getPrice(){
     var price  = $("#gid option:selected").attr("title");
     $('#need').val('￥'+price);
     getKc();
     getInfo();
}

//*******************提交按钮************************
  $("#submit_buy").click(function(){
    var a = $('#kc').attr("alt");
    if(a <= 0){
      layer.msg('该商品库存不足，无法购买！');
      return;
    }
    var gName = $("#gid").val();//获取商品名称<展示>
    var gId = $("#gid option:selected").attr("id");//获取商品ID *
    var price = $("#need").val();//获取商品价格<展示>
    var money =$("#gid option:selected").attr("title");;//获取商品价格  *
    var num = $("#lx").val();//获取联系方式 *
    var type = $("input:radio[name='type']:checked").val();//获取付款方式 *
    var payfs = $("input:radio[name='type']:checked").attr("title");//付款方式<展示>
    var out_trade_no = d();//订单编号 *

    var b = checkLx(num);//判断联系方式是否正确

    if(b == false){
      layer.msg('请输入正确的联系方式');
      return;
    }
    if(type == null || type =="" ){
      layer.msg('请选择您的付款方式');
      return;
    }
    if(gId == "" || price == "" || gId == null || price == null){
      layer.msg('当前商品无法创建订单！');
      return;
    }
    var ii = layer.load(2, {shade:[0.1,'#fff']});

    //验证卡密信息
    $.ajax({
      type : "POST",
      url : "{{url_for('faka.Checkgo')}}",
      data : {"goodid":gId},
      dataType : 'json',
      success : function(data) {
        if(data.code == -1){
          layer.close(ii);
          layer.msg('该商品卡密库存不足！无法购买！');
          return;
        }
      },
      error:function(data){
         layer.close(ii);
        layer.msg('服务器错误');
        return;
        }
    });
    layer.close(ii);

    var u = "type="+type+"&name="+gName+"&money="+money+"&out_trade_no="+out_trade_no+"&gid="+gId;

    var str = "请核对订单信息！<br>订单编号："+out_trade_no+
    "<br>商品名称："+gName+
    "<br>商品价格："+price+
    "<br>联系方式："+num+
    "<br>付款方式："+payfs;

    layer.confirm(str, {
        btn: ['立即付款','取消付款'] //按钮
      }, function(){
        //异步创建订单
        var ii = layer.load(2, {shade:[0.1,'#fff']})
        $.ajax({
          type : "POST",
          url : "{{url_for('faka.CreateOrder')}}",
          data : {"out_trade_no":out_trade_no,"gid":gId,"rel":num},
          dataType : 'json',
          //timeout : 5000,
          success : function(data) {
             layer.close(ii);
             if(data.code != 0){
                layer.msg('服务器错误');
                return false;
              }
              else{
                var qr=data.qr;
                str="微信扫码支付<br><img src='http://qr.liantu.com/api.php?&w=200&text="+qr+"'>";
                if (ispc==false){
                  var ifr = document.createElement('iframe');
                  ifr.src ='http://www.baidu.com';
                  ifr.style.display = 'none';
                  document.body.appendChild(ifr);
                }
                layer.confirm(str, {
                    btn: ['已付款','取消付款'] //按钮
                  },function(index){
                  //do something
                  window.location.reload();
                  layer.close(index);
                });
              }
          },
          error:function(data){
             layer.close(ii);
            layer.msg('服务器错误');
            return false;
            }
        })
        //*********************************************


      }, function(){
        layer.msg('请认真选择您要购买的商品，本站已开启黑名单记录，不良操作会导致您无法继续使用本站', {
          time: 5000, //20s后自动关闭
          btn: ['明白了']
        });
      });
  })
//生成单号
function d(){
   var d=new Date() ;
   var e;
   e=d.getFullYear()+""+d.getMonth()+""+d.getDate()+""+d.getHours()+""+d.getMinutes()+""+d.getMilliseconds();
   return e;
}

//判断联系方式是否未数字
function checkLx(num){
  var t=num;//这个就是我们要判断的值了
  if(!isNaN(t) && t !=""){
   return true;
  }else{
    return false;
  }
}

</script>
<script type="text/javascript">
$(function(){
  //获取商品
  getPoint($("#tp_tid"));
})
</script>

{%endblock content%}